name: Build Validation

on:
  push:
    branches:
      - master 
      - develop 
      - 'feature/**'
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
      env:
        CI_BUILD: true

    # Comentado até ter testes implementados
    # - name: Run tests
    #   run: dotnet test --no-build --configuration Release
